/* AUTHOR: MATTHEW AQUILES
** WALLETLESS LLC
** DATE LAST EDITED: 3/1/2017
** NOTES: FILE GENERATED BY EXPRESS GENERATE, EDITED BY MATTHEW AQUILES; DEFINES A ROUTE TO SERVE THE HOMEPAGE
** TODO: WANT TO MAKE THIS SERVE THE WEBAPP THAT GREG MADE
*/

var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express' });
});

module.exports = router;
