# Uncomment this line to define a global platform for your project
  platform :ios, '9.0'

target 'Medical_App' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Medical_App
  pod 'Alamofire', '~> 4.4’
  pod 'RealmSwift'
  pod 'SwiftyJSON'

  target 'Medical_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end