package walletless.web;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import walletless.dao.UserAccountsRepository;
import walletless.domain.UserAccounts;

@Controller
@RequestMapping(path = "api/userAccounts")
public class UserAccountsController {
	@Autowired // This means to get the bean called userAccountsRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserAccountsRepository userAccountsRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String username, @RequestParam String password, @RequestParam int acctType, @RequestParam Date createDate, @RequestParam int isActive) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		UserAccounts n = new UserAccounts();
		n.setUsername(username);
		n.setPassword(password);
		n.setAcctType(acctType);
		n.setCreateDate(createDate);
		n.setIsActive(isActive);

		userAccountsRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<UserAccounts> getAllUsers() {
		// This returns a JSON or XML with the users
		return userAccountsRepository.findAll();
		//where does this findAll method come from??
	}
}